Repository SKF/ferris, pull requests merged in 2021-07, with the labels that each got.

#144 New ADRs
  docs/adr/007-atoms-vs-components.md
  docs/adr/008-component-naming.md
Labels: documentation

#148 Docs(Storybook): Upgrade to 6.3.2
  package.json
  yarn.lock
Labels: architechture, documentation

#147 Feature/145 add onboarding to readme
  README.md
Labels: documentation

#149 Feature/component list
  docs/components.md
Labels: documentation

#151 Feature/150 auto a11y tests
  docs/adr/009-automatic-a11y-testing.md
  jest.config.js
  jest.setup.ts
  package.json
  src/components/button/Button.test.tsx
  src/components/heading/Heading.test.tsx
  src/components/icon/Icon.test.tsx
  src/components/input-text-field/InputTextField.test.tsx
  src/components/loader/Loader.test.tsx
  src/components/loader/Loader.tsx
  src/components/progress-bar/ProgressBar.test.tsx
  src/components/row/Row.test.tsx
  src/components/spacer/Spacer.test.tsx
  src/components/text-area-field/TextAreaField.test.tsx
  yarn.lock
Labels: documentation, tests

#152 Add stylelint-config-prettier
  .stylelintrc
  package.json
  yarn.lock
Labels: config

#154 feature/153_atomic_design
  README.md
  docs/adr/007-atoms-vs-components.md
  docs/adr/008-component-naming.md
  docs/adr/010-atomic-design.md
  jest.config.js
  src/atoms/button/Button.Link.stories.tsx
  src/atoms/button/Button.Primary.stories.tsx
  src/atoms/button/Button.Secondary.stories.tsx
  src/atoms/button/Button.test.tsx
  src/atoms/button/Button.tsx
  src/atoms/heading/Heading.stories.tsx
  src/atoms/heading/Heading.test.tsx
  src/atoms/heading/Heading.tsx
  src/atoms/icon/Icon.stories.tsx
  src/atoms/icon/Icon.test.tsx
  src/atoms/icon/Icon.tsx
  src/atoms/input-text/InputText.stories.tsx
  src/atoms/input-text/InputText.tsx
  src/atoms/label/Label.stories.tsx
  src/atoms/loader/Loader.stories.tsx
  src/atoms/loader/Loader.test.tsx
  src/atoms/loader/Loader.tsx
  src/atoms/progress-bar/ProgressBar.stories.tsx
  src/atoms/progress-bar/ProgressBar.test.tsx
  src/atoms/progress-bar/ProgressBar.tsx
  src/atoms/row/Row.stories.tsx
  src/atoms/row/Row.test.tsx
  src/atoms/row/Row.tsx
  src/atoms/spacer/Spacer.stories.tsx
  src/atoms/spacer/Spacer.test.tsx
  src/atoms/spacer/Spacer.tsx
  src/atoms/text-area/TextArea.stories.tsx
  src/components/button/Button.Tokens.ts
  src/index.ts
  src/molecules/input-text-field/InputTextField.stories.tsx
  src/molecules/input-text-field/InputTextField.test.tsx
  src/molecules/input-text-field/InputTextField.tsx
  src/molecules/text-area-field/TextAreaField.stories.tsx
  src/molecules/text-area-field/TextAreaField.test.tsx
  src/molecules/text-area-field/TextAreaField.tsx
  tsconfig.json
Labels: architechture, documentation, storybook

#156 Feature/12 modal
  .eslintrc.json
  .storybook/preview.js
  .stylelintrc
  assets/icons/Close.svg
  jest.config.js
  jest.setup.ts
  package.json
  scripts/generate-index.js
  src/atoms/button/Button.Primary.stories.tsx
  src/atoms/heading/Heading.stories.tsx
  src/atoms/heading/Heading.test.tsx
  src/atoms/heading/Heading.tsx
  src/atoms/icon/Icon.stories.tsx
  src/atoms/loader/Loader.stories.tsx
  src/atoms/progress-bar/ProgressBar.stories.tsx
  src/atoms/progress-bar/ProgressBar.test.tsx
  src/atoms/row/Row.stories.tsx
  src/atoms/spacer/Spacer.stories.tsx
  src/common/interfaces.ts
  src/common/styles.ts
  src/index.ts
  src/molecules/input-text-field/InputTextField.stories.tsx
  src/molecules/modal/Modal.stories.tsx
  src/molecules/modal/Modal.test.tsx
  src/molecules/modal/Modal.tsx
  src/molecules/text-area-field/TextAreaField.stories.tsx
  src/tokens/icons/Icons.ts
  src/tokens/icons/components/Close.tsx
  yarn.lock
Labels: component/modal, config, documentation, storybook, tests

#158 Feature/11 checkbox
  package.json
  src/atoms/button/Button.Link.stories.tsx
  src/atoms/button/Button.tsx
  src/atoms/checkbox/Checkbox.Small.stories.tsx
  src/atoms/checkbox/Checkbox.stories.tsx
  src/atoms/checkbox/Checkbox.test.tsx
  src/atoms/checkbox/Checkbox.tsx
  src/atoms/label/Label.Small.stories.tsx
  src/atoms/label/Label.stories.tsx
  src/atoms/label/Label.tsx
  src/atoms/loader/Loader.tsx
  src/atoms/progress-bar/ProgressBar.stories.tsx
  src/common/styles.ts
  src/index.ts
  src/molecules/checkbox-field/CheckboxField.Small.stories.tsx
  src/molecules/checkbox-field/CheckboxField.stories.tsx
  src/molecules/checkbox-field/CheckboxField.test.tsx
  src/molecules/checkbox-field/CheckboxField.tsx
  src/molecules/input-text-field/InputTextField.stories.tsx
  src/molecules/input-text-field/InputTextField.tsx
  src/molecules/text-area-field/TextAreaField.stories.tsx
  src/molecules/text-area-field/TextAreaField.tsx
  yarn.lock
Labels: component/input-checkbox-field, documentation, storybook, tests
