Repository SKF/ferris, pull requests merged in 2021-06, with the labels that each got.

#86 git-flow
  .github/workflows/ci.yaml
  docs/adr/005-git-flow.md
Labels: documentation, project structure

#74 README_Updates
  README.md
  package.json
Labels: architechture, documentation

#91 Updated husky related files
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: architechture

#92 Autogenerate Index.ts
  package.json
  scripts/generate-index.js
  src/index.ts
  yarn.lock
Labels: architechture, enhancement

#89 Feature/expand test examples
  src/components/button/Button.Link.Stories.tsx
  src/components/button/Button.Link.stories.tsx
  src/components/button/Button.Tokens.ts
  src/components/button/Button.test.tsx
Labels: component/button, enhancement

#93 Commitlint
  .commitlintrc.js
  .husky/commit-msg
  README.md
  docs/adr/006-commitlint.md
  package.json
  yarn.lock
Labels: architechture, enhancement

#98 Remove idiomatic order
  .stylelintrc
  package.json
  src/atoms/label/Label.tsx
  src/atoms/text-input/TextInput.tsx
  src/components/button/Button.tsx
  yarn.lock
Labels: architechture

#104 Feature/101 global styles
  src/common/global-styles/GlobalStyles.tsx
  src/components/button/Button.Primary.Stories.tsx
  src/components/button/Button.Primary.stories.tsx
  src/components/text-field/TextField.stories.tsx
Labels: architechture, enhancement

#106 Tokens Update
  package.json
  src/tokens/colors/Colors.ts
  src/tokens/font-sizes/FontSizes.ts
  src/tokens/font-weights/FontWeights.ts
  src/tokens/fonts/Fonts.ts
  src/tokens/line-heights/LineHeights.ts
  src/tokens/sizes/Sizes.ts
  src/tokens/spacings/Spacings.ts
  style-dictionary.config.js
Labels: architechture, enhancement

#107 Fix(GenerateIndex): Added globalstyles to be ignored from props export
  scripts/generate-index.js
  src/index.ts
Labels: architechture

#111 Style Dictionary Update
  package.json
  scripts/jsonToTsEnum.js
  style-dictionary.config.js
  yarn.lock
Labels: architechture, enhancement

#112 Row and Spacer component
  src/components/button/Button.tsx
  src/components/row/Row.stories.tsx
  src/components/row/Row.tsx
  src/components/spacer/Spacer.stories.tsx
  src/components/spacer/Spacer.tsx
  src/tokens/colors/Colors.ts
  src/tokens/font-sizes/FontSizes.ts
  src/tokens/font-weights/FontWeights.ts
  src/tokens/fonts/Fonts.ts
  src/tokens/line-heights/LineHeights.ts
  src/tokens/sizes/Sizes.ts
  src/tokens/spacings/Spacings.ts
  style-dictionary.config.js
Labels: component/row, component/spacer

#113 Heading Component
  src/components/heading/Heading.stories.tsx
  src/components/heading/Heading.tsx
  src/components/title/Title.tsx
  src/index.ts
  src/tokens/headings/Headings.ts
  style-dictionary.config.js
  tsconfig.json
Labels: component/heading

#115 Storybook and Global Styles
  .storybook/preview.js
  src/components/button/Button.Primary.stories.tsx
  src/components/heading/Heading.stories.tsx
  src/components/text-field/TextField.stories.tsx
  src/index.ts
Labels: architechture, enhancement

#118 Progress Bar
  .stylelintrc
  src/components/progress-bar/ProgressBar.stories.tsx
  src/components/progress-bar/ProgressBar.tsx
  src/index.ts
Labels: component/progress-bar

#120 Create component: Loader
  src/components/heading/Heading.tsx
  src/components/loader/Loader.stories.tsx
  src/components/loader/Loader.tsx
  src/index.ts
Labels: component/loader, enhancement

#122 Component: TextAreaField
  src/atoms/input-text/InputText.tsx
  src/atoms/label/Label.tsx
  src/atoms/text-area/TextArea.tsx
  src/atoms/text-input/TextInput.tsx
  src/components/input-text-field/InputTextField.stories.tsx
  src/components/input-text-field/InputTextField.tsx
  src/components/text-area-field/TextAreaField.stories.tsx
  src/components/text-area-field/TextAreaField.tsx
  src/components/text-field/TextField.stories.tsx
  src/components/text-field/TextField.tsx
  src/index.ts
Labels: atom/text-area, component/text-area-field

#123 Styled Components Naming Update
  src/components/button/Button.tsx
  src/components/heading/Heading.tsx
  src/components/loader/Loader.tsx
  src/components/progress-bar/ProgressBar.tsx
  src/components/row/Row.tsx
  src/components/spacer/Spacer.tsx
Labels: architechture, enhancement

#136 Storybook sorting order
  src/atoms/input-text/InputText.stories.tsx
  src/atoms/input-text/InputText.tsx
  src/atoms/label/Label.stories.tsx
  src/atoms/text-area/TextArea.stories.tsx
  src/atoms/text-area/TextArea.tsx
  src/components/button/Button.Link.stories.tsx
  src/components/button/Button.Primary.stories.tsx
  src/components/button/Button.Secondary.stories.tsx
  src/components/heading/Heading.stories.tsx
  src/components/icon/Icon.stories.tsx
  src/components/input-text-field/InputTextField.stories.tsx
  src/components/input-text-field/InputTextField.tsx
  src/components/loader/Loader.stories.tsx
  src/components/progress-bar/ProgressBar.stories.tsx
  src/components/row/Row.stories.tsx
  src/components/spacer/Spacer.stories.tsx
  src/components/text-area-field/TextAreaField.stories.tsx
  src/components/text-area-field/TextAreaField.tsx
Labels: storybook

#137 Set up unit tests
  jest.config.js
  package.json
  src/atoms/input-text/InputText.tsx
  src/atoms/text-area/TextArea.tsx
  src/components/button/Button.test.tsx
  src/components/heading/Heading.stories.tsx
  src/components/heading/Heading.test.tsx
  src/components/icon/Icon.stories.tsx
  src/components/icon/Icon.test.tsx
  src/components/input-text-field/InputTextField.stories.tsx
  src/components/input-text-field/InputTextField.test.tsx
  src/components/input-text-field/InputTextField.tsx
  src/components/progress-bar/ProgressBar.test.tsx
  src/components/row/Row.test.tsx
  src/components/text-area-field/TextAreaField.test.tsx
  src/components/text-area-field/TextAreaField.tsx
  src/tokens/icons/components/Check.tsx
  src/tokens/icons/components/CloseAllFaults.tsx
  src/tokens/icons/components/CloseFault.tsx
  src/tokens/icons/components/OpenInNew.tsx
  yarn.lock
Labels: tests

#139 Add sample app to ferris readme
  README.md
Labels: documentation

#141 Refactor(Commitlint): Add Build and Config types
  .commitlintrc.js
  README.md
Labels: architechture

#142 Feature/138 storybook arg types
  package.json
  src/components/row/Row.stories.tsx
  yarn.lock
Labels: storybook

#143 feature/130_script_updates
  .commitlintrc.js
  README.md
  package.json
  scripts/generate-index.js
  src/index.ts
  src/tokens/icons/components/Check.tsx
  src/tokens/icons/components/CloseAllFaults.tsx
  src/tokens/icons/components/CloseFault.tsx
  src/tokens/icons/components/OpenInNew.tsx
Labels: scripts
